version: 0.2
phases:
  pre_build:
    commands:
      - echo "logging in to docker hub"
      - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - commit_hash=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=$commit_hash
      - version="latest"
      - IMAGE_URI_UNIQUE="$DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG-$version"
      - IMAGE_URI_READABLE="$DOCKER_USERNAME/$IMAGE_NAME:$version"
  build:
    commands:
      - echo "building the docker image"
      - docker build -t $IMAGE_URI_UNIQUE .
  post_build:
    commands:
      - echo "pushing the docker image to docker hub"
      - docker tag $IMAGE_URI_UNIQUE $IMAGE_URI_READABLE
      - docker push $IMAGE_URI_UNIQUE
      - docker push $IMAGE_URI_READABLE
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
      - kubectl rollout restart deployment/brain-tasks-app -n test
      - echo "waiting for LoadBalancer to be ready"
      - for i in {1..30}; do
          LB_DNS=$(kubectl get svc brain-tasks-app-service -n $K8S_NAMESPACE -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          if [ -n "$LB_DNS" ]; then
            echo "Application URL: http://$LB_DNS:3000"
            break
          fi
          echo "Waiting for LoadBalancer..."
          sleep 10
        done


# version: 0.2

# phases:
#   build:
#     commands:
#       - echo "Checking Docker"
#       - docker version
#       - docker info